#!/bin/bash
#
# check that the file ls in the current directory runs - Should displays 'cisfun'

command="./ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file

# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
res=`$CAT "$OUTPUTFILE"`
if [ "$res" == "cisfun" ]; then
    print_ok
else
    print_ko
fi

# clean up
stop_shell
$RM -f $tmp_file

