#!/bin/bash
#check that the PATH is checked in the right order
#CHECK  IN THE CWD

command="ls"
tmp_file="checker_tmp_file_$RANDOM"
save_file=`echo $BASH_SOURCE | sed -e 's/\.\///g' -e 's/\//#/g'`

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# empty PATH
OLDPATH="$PATH"
PATH="::$PATH::"

# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# copy saved output for debugging
cat $OUTPUTFILE > "$SAVEOUTPUTDIR/$save_file"

# check the result
res=`$CAT "$OUTPUTFILE"`
if [ "$res" == "cisfun" ]; then
    print_ok
        else
            print_ko
                fi

# clean up
                stop_shell
